name: TVPL Crawler

on:
  workflow_dispatch:
    inputs:
      CRAWLEE_PURGE_ON_START:
        type: boolean
        description: 'Purge storage on start'
        default: false
      MAX_REQUESTS_PER_CRAWL:
        type: number
        description: 'Max requests per crawl'
        default: 100
      MAX_CONCURRENCY:
        type: number
        description: 'Max concurrency'
        default: 5
  repository_dispatch:
    types: [TVPL_CRAWLER_RUN]

env:
  CI_RUNNER: true
  CRAWLEE_STORAGE_DIR: 'storage'
  CRAWLEE_PURGE_ON_START: ${{ (github.event.inputs.CRAWLEE_PURGE_ON_START == 'true') && '1' || '0' }}
  MAX_REQUESTS_PER_CRAWL: ${{ github.event.inputs.MAX_REQUESTS_PER_CRAWL || github.event.client_payload.MAX_REQUESTS_PER_CRAWL || 50 }}
  MAX_CONCURRENCY: ${{ github.event.inputs.MAX_CONCURRENCY || github.event.client_payload.MAX_CONCURRENCY || 5 }}
  TVPL_USERNAME: ${{ secrets.TVPL_USERNAME }}
  TVPL_PASSWORD: ${{ secrets.TVPL_PASSWORD }}
  TVPL_MEMBER_GA: ${{ secrets.TVPL_MEMBER_GA }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: |
            ${{ env.STORE_PATH }}
            /home/runner/.cache/
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Restore crawlee storage
        uses: actions/cache/restore@v3
        with:
          path: |
            /home/runner/work/sifu/sifu/.cookies.json
            /home/runner/work/sifu/sifu/storage
          key: ${{ runner.os }}-storage-${{ hashFiles('**/.last-crawl') }}
          restore-keys: |
            ${{ runner.os }}-storage

      - name: Install dependencies
        run: pnpm install

      - name: Run
        run: |
          echo CRAWLEE_PURGE_ON_START=${{ env.CRAWLEE_PURGE_ON_START }}
          CRAWLEE_PURGE_ON_START=${{ env.CRAWLEE_PURGE_ON_START }} pnpm start:ci
        continue-on-error: true

      - name: Dump current time to .last-crawl
        run: |
          echo $(date +%s) > .last-crawl
          cat .last-crawl

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          message: 'chore(documents): update documents [skip ci]'

      - name: Save crawlee storage
        uses: actions/cache/save@v3
        with:
          key: ${{ runner.os }}-storage-${{ hashFiles('**/.last-crawl') }}
          path: |
            /home/runner/work/sifu/sifu/.cookies.json
            /home/runner/work/sifu/sifu/storage

      - name: Dispatch trigger
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ github.repository }}
          event-type: TVPL_CRAWLER_RUN
          client-payload: '{ "MAX_REQUESTS_PER_CRAWL": ${{ env.MAX_REQUESTS_PER_CRAWL }}, "MAX_CONCURRENCY": ${{ env.MAX_CONCURRENCY }} }'
